### ISSUE TITLE
Conda install should not include "pyqt"

### ISSUE THREAD

**Issue by sbrugman** [conda-forge/pandas-profiling-feedstock#23]
Running conda install will also install qt (nearly 100mb):

`conda install -c conda-forge pandas-profiling`

Pandas-profiling does not rely on this dependency (altough it's optional for experimental features).
Where does this dependency come from and how can we remove it?

**Comment by xhochy** [comment]
You could use the tool conda-tree to inspect where this is coming from.

**Comment by sbrugman** [comment]
The dependency was coming from https://github.com/conda-forge/phik-feedstock and is now resolved.
